export const CREATE_ORDER_REQUST = 'CREATE_ORDER_REQUST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE' 

export const GET_ORDER_BY__ID_REQUST = 'GET_ORDER_BY__ID_REQUST'
export const GET_ORDER_BY__ID_SUCCESS = 'GET_ORDER_BY__ID_SUCCESS'
export const GET_ORDER_BY__ID_FAILURE = 'GET_ORDER_BY__ID_FAILURE' 